### ISSUE TITLE
(Assistance) Minor improvements

### ISSUE THREAD

**Issue by mark01zlatar** [4lessandrodev/types-ddd#113]
### Before everything: 
Just want to say thanks for the lib, I believe you did a great job here.
### Short Background: 
Been working with Typescript for about 2 years now. For the last 3-4 months I've been playing with DDD in typescript, learning about DDD, and was basically implementing something similar you have here(note: you did a much better job in every aspect :slightly_smiling_face: ).

For the last few days, I was playing with this lib, looking at source code, and implementing types-ddd to the existing project(to see how things are going to play).

About the project(won't go too much in details): 
- I implemented a serverless microservice event-driven architecture and so far it's going well.
- Hosting is done on AWS (CDK IaC)
- Because of AWS lambda usage(serverless architecture), there we difficulties that I had to overcome and that I'm still working on...

### Small Changes/Features Proposals 
All changes are around the same things basically :) 
1.  Friendly Imports - better Barrel exports
Currently If i don't want to import whole lib, but to use individual modules(e.g only Core and Repo) i have to do something like:
```typescript
import { Result } from "types-ddd/dist/core/result";
import { AggregateRoot } from "types-ddd/dist/core/entity";
import { BaseDomainEntity } from "types-ddd/dist/core/base-domain-entity";
```
You did a good job with modules organization, so with a few simple changes we could have something like:
```typescript
import { Result, AggregateRoot, BaseDomainEntity } from "types-ddd/dist/core";
```
or we could even think about better organization in general.. for now, this would be good enough(build would be much smaller and imports would be simpler)
2. Decoupling - making utils optional and decoupled from other modules,  removing dependencies(e.g bcrypt)
Installing this lib made the project from `found 0 vulnerabilities` to `2 vulnerabilities (1 moderate, 1 high)` even though 0 dependencies were used in the project(both auth and logs we already implemented)..
After digging I found out that "bcrypt" was the issue, this was solved by previously mentioned imports..
3. Lib Logging
Instead of having pino + pino-pretty that log everything constantly we could use [debug](https://www.npmjs.com/package/debug). Separate logs per module/feature/component and then show them only explicitly when needed.
Note that [pino-debug](https://github.com/pinojs/pino-debug) also exists.
3. toObject without mapper -> autoConvertDomainToObject 
Saw that this was in beta and after testing found out that the results were not as expected.. even though I wrote getters on aggregate after conversion some properties were undefined (I'm probably missing something and I'll have to dig into the source more to understand what's going on).
Ultimately, the feature would speed up the process(conversion/mapping) so I'm looking forward to id :slightly_smiling_face: 

### Final thoughts:
- I know that DDD is slow/bulky to implement and that serverless architecture maybe not be the best choice... For now, it plays extremely well but we will see it as the project scale, let me know what do you think(and thanks in advance). 
- New approach for the entity creation looks really nice, would love to support you on this
- So far codebase seems great and would love to contribute

Also note: If I continue to use this lib and the project goes well, you can expect donations for sure..

**Comment by 4lessandrodev** [comment]
First, @mark01zlatar  thank you very much for the feedback and thank you for suggesting improvements, the idea of making the library public is precisely to improve it with the community. :+1: 

About the improvements of "imports" the implementation makes sense, I opened an issue for it.
1 - Issue #114 

Make the library core independent of third-party libraries. I had already thought about implementing the separation of responsibilities, but I haven't had time to do it yet, because I believe it will take a while.
2 - Issue #115 

About Logger only two resources use it, "Domain Events" and Errors generated by "Result". It makes sense to set the Logger optionally for "Domain Events", but I see it's important to keep the logs for "Result" so that errors occur when there is a wrong implementation.
3 - Issue #116 

About the toObject function I would like you to share a model that I can simulate, so I can correct any errors.

thank you so much!

**Comment by mark01zlatar** [comment]
@4lessandrodev cool, glad to hear that :raised_hands: 

regarding toObject function, if we take a look at auto-mapper.spec.ts file:
- when we add any primitive value to props(e.g isPublicProfile: boolean) that property would be undefined
- also, seems that if we have complex value-object, value would be skipped/undefined
```typescript
	interface SocialInfoVOProps {
		links: string[],
		publicEmail?: EmailValueObject
	}
	
	class SocialInfoVO extends ValueObject<SocialInfoVOProps> {
		public static MAX_LINKS = 5;

		constructor(props: SocialInfoVOProps) {
			super(props)
		}

		get links() {
			return this.props.links
		}
		get publicEmail() {
			return this.props.publicEmail
		}
		
		public static create(props: { links: string[], email: string }): Result<SocialInfoVO> {
			//... validate and do stuff
			return Result.ok(new SocialInfoVO(...)) 
		}
	}
```
seems that value-object conversion needs to be changed/improved

I would love to help you with issues, let me know the best way to contribute :slightly_smiling_face:

**Comment by 4lessandrodev** [comment]
@mark01zlatar Thanks for sharing the bug, it was simple to fix.

Glad to hear you're excited to contribute, the prettier one is working (on my machine at least), the case is I've set it up similar to the C environment, it's quite different from the javascript approach.

Feel free to configure husk and lint-staged, I use them in my projects and I like them.
In my mind, I think it might work like the example below:

Before commit hook:
- Validate build and circular imports (see scripts on package.json "prebuild")
- run prettier

Before push hook:
- Run all tests

But feel free to state what you think.

Next steps:
- Just open a issue for It, 
- Fork the project and hands on,
- On done open a pull request from your fork to this project 

Any question feel free to ask me!!!

**Comment by mark01zlatar** [comment]
@4lessandrodev got it, thanks for the info, there will be more questions for sure :smile: 
i'll create a new issue regarding clean-code tooling(we can continue the discussion there), PR will be completed today probably..
