### ISSUE TITLE
Bug trying to implement an ObjectValue in NextJs

### ISSUE THREAD

**Issue by tamon-persol** [4lessandrodev/types-ddd#176]
**Describe the bug**
When i try to create a an ObjectValue  it throw an error.
` Module not found: Can't resolve 'fs'`

**To Reproduce**
ObjectValue
```
import { IResult, Result, ValueObject } from 'types-ddd';

export interface NameProps {
  value: string;
}

export class Name extends ValueObject<NameProps> {
  private constructor(props: NameProps) {
    super(props);
  }

  public static create(props: NameProps): IResult<Name> {
    return Result.Ok(new Name(props));
  }
}

export default Name;

```

```
const Home: NextPage = () => {
  Name.create({value : 'tamon'})

  return (
    <div className={styles.container}>
    </div>
  );
};

```

Error Thrown
<img width="679" alt="Screen Shot 2022-09-14 at 6 05 32" src="https://user-images.githubusercontent.com/60681425/190009717-acb5b823-cb77-4263-a6d0-59b67a9ec898.png">

**Comment by 4lessandrodev** [comment]
hey @tamon-persol  thanks for reporting this.
This is not a bug of the "types-ddd" lib, this is a limitation of the way next.js generates a package for the browser, but you can change your settings.

try putting this in your package.json

``` json
  "browser": {
    "fs": false,
    "path": false,
    "os": false,
    "child_process": false
  }
```

The "types-ddd" lib uses some dependencies that might not be available to the browser if webpack removes them.
Also check your webpack configuration if you are not removing packages used by "types-ddd" like:
- bcrypt
- pin
- cute pin
- rich domain

Alternative: you can use "rich-domain" which is free from 3rd party dependency

**Comment by mmmoli** [comment]
Still stuck on this.

I'm using nextjs@13.4.4
I'm calling my api from a route handler.

I've tried:
- adding contents to package.json
- migrating to "rich-domain"

**Comment by 4lessandrodev** [comment]
Can you send some example?

Check this: [Sample](https://github.com/4lessandrodev/fix-next-rich-domain/tree/main)

**Comment by mmmoli** [comment]
My project is now working (see repo) with the following setup:

1. Nextjs edge router
2. Replace `types-ddd` dep with `rich-domain`
3. Addition to package.json:
```
   "browser": {
    "crypto": false
   },
  ```

**Comment by 4lessandrodev** [comment]
Perfect @mmmoli,

The types-ddd library uses some dependencies like:

- bcrypt
- pino
- pino-pretty
- rich-domain (core)
So the build removes them; however, rich-domain uses only native cryptography (crypto) to generate UUID. In case the crypto module is not available, a native implementation will be used to ensure UUID generation.

I checked, and we don't have a bug, right?

<img width="770" alt="image" src="https://github.com/4lessandrodev/types-ddd/assets/34426407/f86fc664-dd16-4ee3-9249-11f37ecd5ce8">

<img width="714" alt="image" src="https://github.com/4lessandrodev/types-ddd/assets/34426407/50a3e52f-52d1-47da-9fcb-373d5634b353">

**Comment by mmmoli** [comment]
Confirm: no bug!
