### ISSUE TITLE
Dúvida, PasswordValueObject

### ISSUE THREAD

**Issue by vinicius-arcanjo** [4lessandrodev/types-ddd#189]
@4lessandrodev, eu procurei na doc porem não achei sobre a validação, eu vi que eu posso usar `validation(value: string): boolean;` porem vi que ele valida `5` caracteres, se eu precisar aumentar esse valor para `8` por exemplo, qual seria o melhor caminho?

Uma outra duvida que surgiu, qual a diferença desse repositório `type-ddd` e o repositório `rich-domain`?

**Comment by 4lessandrodev** [comment]
Olá @vinicius-arcanjo beleza? 
`validation` é uma função utilitária disponível em qualquer entidade ou objeto de valor, e ele possui vários métodos de validação, dentre elas o método string.

Para validar o tamanho da string você pode utilizá-lo da seguinte maneira:

```ts

const min = 1;
const max = 8;

const isValid = validation.string("some value").hasLengthBetween(min, max);

```

Em relação à diferença da lib "rich-domain" e "types-ddd" você pode dar uma olhada nessa issue [aqui](https://github.com/4lessandrodev/rich-domain/issues/1).

**Comment by vinicius-arcanjo** [comment]
Obrigado por responder rápido @4lessandrodev, porem não tenho certeza se entendi, nesse exemplo que você citou, você diz para eu usar o Validator, correto?

```ts
import { Validator } from 'types-ddd'

const validation = Validator.create()
const isValid = validation.string(Password).hasLengthBetween(6, 20)
``` 

Porem eu estava me referindo ao `validation` que existe dentro do próprio `PasswordValueObject`, exemplo:

```ts
validation(value: string): boolean {
		return PasswordValueObject.isValidProps(value);
	}

	/**
	 *
	 * @param value check if password has a valid value length
	 * @returns true if is all ok or false else not
	 */
	public static isValidProps(value: string): boolean {
		const maxLength = 22;
		const minLength = 5;
		const { string } = this.validator;
		if (!PasswordValueObject.isEncrypted(value)) {
			const passwordHasRequiredLength = string(value).hasLengthBetween(
				minLength,
				maxLength
			);
			return passwordHasRequiredLength;
		}
		return true;
	}
```

na linha 	`const maxLength = 22;` e `const minLength = 5;` eu conseguiria passar um valor para isso?

**Comment by 4lessandrodev** [comment]
a partir da versão 3.2.2 você pode customizar da seguinte maneira 

- em um arquivo importe a senha 
- utilizando o método set de`Reflect` defina as propriedades `MAX_LENGTH` e `MIN_LENGTH` com os valores desejados
- exporte sua senha customizada

/** my-custom-password.ts */

```ts

import { PasswordValueObject } from "types-ddd";

Reflect.set(PasswordValueObject, 'MAX_LENGTH', 22);
Reflect.set(PasswordValueObject, 'MIN_LENGTH', 10);

export { PasswordValueObject as MyCustomPassword };

```
