### ISSUE TITLE
Add methods for return only numbers and no special caracter in custom-string.value-object

### ISSUE THREAD

**Issue by VinnyLima** [4lessandrodev/types-ddd#223]
**Is your feature request related to a problem? Please describe.**
There was a need for methods to clean up the special characters in a string and return only the numbers, it would be interesting if these two methods were implemented.

**Describe the solution you'd like**
A possible solutions
![image](https://user-images.githubusercontent.com/24688302/211885282-2be4c4ec-d190-405d-ae79-6755c2244b46.png)

**Comment by 4lessandrodev** [comment]
published 3.4.4 :tada:
