### ISSUE TITLE
Entity method toObject() not inferring type from entity props

### ISSUE THREAD

**Issue by dayatwork** [4lessandrodev/types-ddd#281]
Thanks for this great libs. 

I tried to learn DDD using this library and your example in this repo: https://github.com/4lessandrodev/ddd-app/blob/main/src/modules/product/domain/test/product.aggregate.spec.ts

In your example repo (version 3.5.1) it can be seen that the toObject() method returns the correct type
![image](https://github.com/4lessandrodev/types-ddd/assets/79784355/bb96de21-4e04-48e9-806c-2d1feec6a685)

and it doesn't work in version 3.6.2 and I have to manually input the generic parameter to get the correct type

![image](https://github.com/4lessandrodev/types-ddd/assets/79784355/d6c78451-0458-4aca-90b6-0cee1d530934)

![image](https://github.com/4lessandrodev/types-ddd/assets/79784355/88abbfa4-3a7f-4b83-b20c-c3aac1156612)

Thank you

**Comment by 4lessandrodev** [comment]
hey @dayatwork thanks for reporting...

I updated the sample to new version and It keep working. Could you show what the `create` "factory" method was defined? it returns the your class type? typing is applied dynamically according to the return and to be correctly inferred it needs to return an instance with the same type as the inferred class.

Example:

```ts
	class Product extends Entity<Props> {
		private constructor(props: Props) {
			super(props);
		}
		
                public static create(props: Props): Result<Product> {
			return Ok(new Product(props));
		}
	}
```

In the example the method **create** return a type **`Result<Product>`**
