### ISSUE TITLE
Entity Creation - New Approach

### ISSUE THREAD

**Issue by 4lessandrodev** [4lessandrodev/types-ddd#3]
# Entities 

New way to create an entity, value object and aggregate 

```ts

import {  DomainEntity, ValueObject, Entity, DomainId , ID } from '@types-ddd/core';

@DomainEntity({ name: 'User' })
export class UserEntity extends Entity {
   
    @DomainId
    id: ID;
    
    @ValueObject({ name: 'userName', required: true, Length:{ max: 30, min: 3}, type: string })
    userName: UserNameValueObject;
    
    @ValueObject({ name: 'age', type: number, max: 120, min: 1 })
    age: AgeValueObject
    
    @DomainEntity({ type: Array<PostEntity>, required: false, default: [] })
    posts: PostEntity[];

}
```

### References: 

1. [Class Transformer](https://www.npmjs.com/package/class-transformer)
2. [Entity Decorators](https://www.npmjs.com/package/entity-decorators)
3. [Typeorm Entity](https://www.npmjs.com/package/typeorm)

**Comment by ycaruso** [comment]
Hi Alessandro, I'm studying DDD and your project has been helping me, thanks for sharing this.

**Comment by 4lessandrodev** [comment]
> Hi Alessandro, I'm studying DDD and your project has been helping me, thanks for sharing this.

I'm glad to know that... Success!!!
