### ISSUE TITLE
Assistance & Congrats 🤚🏻 🎉 

### ISSUE THREAD

**Issue by rjlopezdev** [4lessandrodev/types-ddd#86]
Hi @4lessandrodev , congrats for this awesome project!

I spent some time evaluating alternatives to use an utility library to develop DDD in TypeScript and this is amazing!

I open this issue to congratulate you on your work and offer you a little help if you need it in any area (new features, debugging, documentation ...)

Congratulations 🎉 !

**Comment by rjlopezdev** [comment]
Hi @4lessandrodev I would like to help you on `Build a CLI to generate a starter module/entity/use-case/aggregate/value-object on some path...`
How can I help you on this task?
Have you already build an cli?

I think it would be very interesting to separate the logic of the scaffolders from the implementation to be able to adapt it to different strategies or tooling (I am thinking of a common cli, a plugin for [Nx](https://nx.dev/) or others)

**Comment by 4lessandrodev** [comment]
Hi @rjlopezdev  good choice!

You may help me open a pull request and create an initial example of how the CLI will works with `nx`. I liked Nx. It's a good tool and it suits us, we can use it.

I've never built a CLI before, but I made some template generators using `plop` you can check this repository [click here](https://github.com/4lessandrodev/nest-template), similar to what we'll do here.

It's a good idea to create a common CLI. We can proceed as you suggested.

**Comment by rjlopezdev** [comment]
Nice @4lessandrodev !

I'll use these template as base for my implementation.

# I share you my Roadmap

1. A `core` implementation of Scaffolding tool (it will **DESCRIBE** available commands (taking `plopfile.js` as reference for developer use cases (create entities, aggregates, value objects...)) & its template files and generators). Example:
 ```typescript 
const typesDDDScaffolder = new TypesDDDScaffolder();
const result = await typesDDDScaffolder.run('add-vo', { name: 'foo', ...});
 ```

```
Output:
=======================

{
  command: 'add-vo',
  actions: [
    {
      type: 'create-file',
      name: 'foo.vo.ts',
      content: '<PROCCESED CONTENT USING HANDLEBARS>'
    }
  ]
}
```
2. A `cli` implementaion (maybe using [Commander](https://www.npmjs.com/package/commander) because we need isolate `cli` logic from its generators & templates). It will use `Output` from `core` as base for create files & directories. Example:
```bash
types-ddd-cli add-vo foo ...
```
3. A `NX Plugin` implementation. As `cli`, it will use `Output` from `core` as base for create files & directories. Example:
```bash
nx run types-ddd:add-vo foo ...
```

What do you think?

One more topic. Do you want that this implementaion take part of this repository or other?

I appreciate your time!
